// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Gejile Hu. All rights reserved.

/// T4's golden regression: a fixed farm, a fixed weather year and a fixed seed,
/// compared point by point against a series committed to the repository.
///
/// **What this catches that nothing else does.** The conservation suite proves
/// the books balance and the validation suite proves the seasonal shape is
/// right, and a change can pass both while quietly moving every number. This
/// suite has no opinion about whether the model is correct - it only says
/// whether it still answers what it answered yesterday, so an unintended change
/// arrives as a failed test rather than as a different figure in a report six
/// months later.
///
/// **The baseline is never regenerated by the thing it judges.** A test that
/// writes its own expectations when they do not match is a test that always
/// passes. Rewriting it takes a deliberate act - `PADDOCK_WRITE_GOLDEN_BASELINE`
/// in the environment - and the diff is then reviewed like any other change,
/// because that diff *is* the record of what the model now says differently.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <paddock/config/ScenarioConfig.hpp>
#include <paddock/config/ScenarioRun.hpp>

#include "../support/ShippedBundle.hpp"

namespace paddock::config {
namespace {

/// The golden scenario: synthetic weather, a subdivided block and ewes on it.
///
/// Chosen because it needs nothing fetched. A bundle whose ground is a LiDAR
/// snapshot would make the baseline depend on a file that is deliberately not
/// committed, and a regression suite that is skipped on a clean checkout is not
/// a gate.
std::string bundle_path() {
  return std::string(PADDOCK_DATA_DIR) + "/scenarios/canterbury-grazed";
}

std::string baseline_path() {
  return std::string(PADDOCK_REGRESSION_BASELINE_DIR) + "/canterbury-grazed.csv";
}

core::DietQuality pasture_diet() {
  core::DietQuality diet;
  diet.metabolisable_energy_mj_per_kg_dm = 10.5;
  diet.digestibility_percent = 75.0;
  return diet;
}

/// One day of the series the baseline pins.
///
/// Four numbers, chosen so that a change anywhere in the coupled system moves at
/// least one of them: cover carries pasture growth and grazing offtake,
/// liveweight carries intake and the energy model, the water growth factor
/// carries the soil water balance, and irrigation carries the schedule's
/// decisions.
struct GoldenDay {
  double cover_kg_dm_per_ha = 0.0;
  double liveweight_kg = 0.0;
  double water_growth_factor = 0.0;
  double irrigation_mm = 0.0;
};

std::vector<GoldenDay> series_of(const RunSummary& run) {
  std::vector<GoldenDay> days;
  days.reserve(run.cover_kg_dm_per_ha.size());
  for (std::size_t day = 0; day < run.cover_kg_dm_per_ha.size(); ++day) {
    GoldenDay entry;
    entry.cover_kg_dm_per_ha = run.cover_kg_dm_per_ha[day];
    entry.liveweight_kg = day < run.liveweight_kg.size() ? run.liveweight_kg[day] : 0.0;
    entry.water_growth_factor = day < run.water_stress.size() ? run.water_stress[day] : 0.0;
    entry.irrigation_mm = day < run.irrigation_mm.size() ? run.irrigation_mm[day] : 0.0;
    days.push_back(entry);
  }
  return days;
}

void write_series(const std::string& path, const std::vector<GoldenDay>& days) {
  std::ofstream out(path);
  ASSERT_TRUE(out) << "cannot write " << path;
  // Seventeen significant digits round-trips an IEEE double exactly, so the
  // baseline is the run rather than a rounding of it.
  out.precision(17);
  out << "day,cover_kg_dm_per_ha,liveweight_kg,water_growth_factor,irrigation_mm\n";
  for (std::size_t day = 0; day < days.size(); ++day) {
    out << day << ',' << days[day].cover_kg_dm_per_ha << ',' << days[day].liveweight_kg << ','
        << days[day].water_growth_factor << ',' << days[day].irrigation_mm << '\n';
  }
}

std::vector<GoldenDay> read_series(const std::string& path) {
  std::vector<GoldenDay> days;
  std::ifstream in(path);
  if (!in) {
    return days;
  }
  std::string line;
  std::getline(in, line);  // header
  while (std::getline(in, line)) {
    if (line.empty()) {
      continue;
    }
    std::istringstream fields(line);
    std::string cell;
    GoldenDay entry;
    std::getline(fields, cell, ',');  // day index, positional
    std::getline(fields, cell, ',');
    entry.cover_kg_dm_per_ha = std::stod(cell);
    std::getline(fields, cell, ',');
    entry.liveweight_kg = std::stod(cell);
    std::getline(fields, cell, ',');
    entry.water_growth_factor = std::stod(cell);
    std::getline(fields, cell, ',');
    entry.irrigation_mm = std::stod(cell);
    days.push_back(entry);
  }
  return days;
}

/// **Why this is a tolerance and not an equality.**
///
/// The determinism property test asserts bit-identical results from the same
/// seed, and it holds - on one machine. This baseline is committed from one
/// platform and checked on three, and `std::exp`, `std::pow` and `std::sin` are
/// not required to agree to the last bit between libm implementations. Over 366
/// coupled days those last bits accumulate.
///
/// 1e-6 relative is far tighter than any change worth making: a real change to
/// the growth, intake or water model moves these numbers by percent, not by
/// parts per million. The absolute floor keeps a day whose value is legitimately
/// near zero - no irrigation, no stress - from failing on noise.
constexpr double kRelativeTolerance = 1e-6;
constexpr double kAbsoluteFloor = 1e-9;

bool agrees(double baseline, double now) {
  const double difference = std::abs(baseline - now);
  return difference <= kAbsoluteFloor + (kRelativeTolerance * std::abs(baseline));
}

RunSummary run_the_golden_scenario() {
  const ScenarioBundle bundle = tests::load_on_flat_ground(bundle_path());
  return run_managed_scenario(bundle, pasture_diet(), "golden");
}

TEST(GoldenScenarioTest, TheYearStillRunsTheWayItRan) {
  const RunSummary run = run_the_golden_scenario();
  const std::vector<GoldenDay> now = series_of(run);
  ASSERT_FALSE(now.empty()) << "the golden scenario produced no days";

  if (std::getenv("PADDOCK_WRITE_GOLDEN_BASELINE") != nullptr) {
    write_series(baseline_path(), now);
    GTEST_SKIP() << "baseline rewritten to " << baseline_path()
                 << " - review the diff, it is the record of what changed";
  }

  const std::vector<GoldenDay> baseline = read_series(baseline_path());
  ASSERT_FALSE(baseline.empty())
      << "no baseline at " << baseline_path()
      << "\nWrite one deliberately: PADDOCK_WRITE_GOLDEN_BASELINE=1 ctest -L regression";

  ASSERT_EQ(baseline.size(), now.size()) << "the run is a different length than the baseline";

  // Every mismatch is written out before the first failure is reported, so a
  // change that moves the whole year is one plot rather than one number.
  const std::string diff_path = std::string(PADDOCK_REGRESSION_OUTPUT_DIR) + "/golden-diff.csv";
  std::ofstream diff(diff_path);
  diff.precision(17);
  diff << "day,series,baseline,now,difference\n";

  int mismatches = 0;
  int first_bad_day = -1;
  for (std::size_t day = 0; day < baseline.size(); ++day) {
    const auto compare = [&](const char* name, double was, double is) {
      diff << day << ',' << name << ',' << was << ',' << is << ',' << (is - was) << '\n';
      if (!agrees(was, is)) {
        ++mismatches;
        if (first_bad_day < 0) {
          first_bad_day = static_cast<int>(day);
        }
      }
    };
    compare("cover_kg_dm_per_ha", baseline[day].cover_kg_dm_per_ha, now[day].cover_kg_dm_per_ha);
    compare("liveweight_kg", baseline[day].liveweight_kg, now[day].liveweight_kg);
    compare("water_growth_factor", baseline[day].water_growth_factor, now[day].water_growth_factor);
    compare("irrigation_mm", baseline[day].irrigation_mm, now[day].irrigation_mm);
  }

  EXPECT_EQ(mismatches, 0) << mismatches << " points differ from the baseline, first on day "
                           << first_bad_day << ".\nThe whole series is in " << diff_path
                           << "\nIf the change was intended, rewrite the baseline with"
                              " PADDOCK_WRITE_GOLDEN_BASELINE=1 and review that diff.";
}

// The totals a report quotes, pinned separately from the series. A change can
// leave the daily shape alone and still move what the year came to.
TEST(GoldenScenarioTest, TheYearStillComesToWhatItCameTo) {
  const RunSummary run = run_the_golden_scenario();

  // Pinned from the run, at the same 1e-6 relative tolerance the series uses and
  // for the same reason: three platforms, one committed set of numbers.
  //
  // **Repinned three times.** The third when nitrate began leaching from the
  // soil's own mineral pool and not only from urine patches (E31): every
  // scenario now loses a little nitrogen to drainage whether or not it carries
  // stock, so this one grows very slightly less.
  //
  // First when the grid stopped overriding the soil file,
  // and again when the nitrogen cycle was closed at the animal: excreta returns
  // to the paddock now instead of leaving with the grazed dry matter, so the
  // sward has nitrogen it did not have and grows more on it. Cover rose another
  // 52 kg DM/ha on the mean.
  //
  // The failure message carries "evaluates to" for every one of these, which is
  // where the new figures come from - no separate mechanism is needed to read
  // them.
  //
  // **When the grid stopped overriding the soil file.** The scenario's
  // soil.toml computes 120 mm of available water and its [grid] section varied
  // that across the farm from 60 to 140 - averaging 100, replacing the profile
  // rather than varying around it, so the soil file was read by nothing. The
  // gradient is now centred on the soil at 100 to 140, and this farm holds a
  // fifth more water than the numbers below were pinned against. Cover rose by
  // 78 kg DM/ha on the mean and the mob was moved once more.
  //
  // **Re-pinned when the scenario became a real farm** (verify.md, E80). This
  // bundle ran a synthetic generator drawing 700-930 mm and a sward whose
  // radiation use efficiency was a placeholder 1.5; it now reads twenty-five
  // years of real Selwyn weather and shares the sourced sward with every other
  // scenario. Nothing about the engine changed, and everything about the farm
  // did:
  //
  //     mean cover    3135 -> 1620 kg DM/ha
  //     lowest cover  1831 ->  769
  //     eaten          125 ->   92 tonnes
  //     mob moves       98 ->   30
  //
  // The old numbers described a farm wetter than Canterbury growing pasture at
  // twice the efficiency anyone has measured. These describe a dryland Selwyn
  // farm, and the mob is moved a third as often because there is a third as
  // much regrowth to move it onto.
  //
  // **Re-pinned again for E83**, which gave tissue turnover its own temperature
  // response instead of running it off a photosynthesis cardinal. Leaf turns
  // over faster in a Canterbury summer than the fitted leaf lifespan it
  // replaced, so the sward carries less and the mob is moved less often:
  // mean cover 1,620 to 1,528, eaten 91.6 to 85.5 tonnes, moves 30 to 24.
  EXPECT_NEAR(run.mean_cover_kg_dm_per_ha(), 1528.441212096667, 1.6e-3);
  EXPECT_NEAR(run.lowest_cover_kg_dm_per_ha(), 728.71497299754617, 7.3e-4);
  EXPECT_NEAR(run.closing_cover_kg_dm, 758.03559544857126, 7.6e-4);
  EXPECT_NEAR(run.eaten_kg_dm, 85495.868074425103, 8.5e-2);
  EXPECT_NEAR(run.closing_liveweight_kg(), 55.000014928809946, 5.5e-5);

  // Counts, so they are equalities. A management decision that moves a mob one
  // more time is a change worth stopping on, not one to absorb in a tolerance.
  EXPECT_EQ(run.moves, 24);
  EXPECT_EQ(run.days_short, 0);
}

}  // namespace
}  // namespace paddock::config
